# Site settings
title: Albretsen
email: asgeir.albretsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a hobbyist website, game and app developer. This is my
  landing site, where you can find all my main projects
  and also read a little about them. I will also happily build
  apps and games for anyone with a good idea! Contact me via
  email or the contact form on this website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://albretsen.github.io/" # the base hostname & protocol for your site
twitter_username: AlbretsenAsgeir
github_username:  Albretsen

# Build settings
markdown: kramdown
